title: "clectricDIY-Guidebook"
description: "The Guidebook for the history and works of the clectricDIY Community."
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: false
